### ISSUE TITLE
error on v9

### ISSUE THREAD

**Issue by mslokhat** [ageorgieff/auto-service#2]
Hi
while installing on v9 :

1. __init__.py
there no controllers to import

2. parse error 
XMLSyntaxError: Opening and ending tag mismatch: group line 152 and page, line 162, column 32

**Comment by AiKiHack** [comment]
Hi
I tested several times and no error ocures (v9 and v10 -its same code)
env- Kubuntu 16.04.1 last upgarde incl. Odoo 20.12.2016
![log](https://cloud.githubusercontent.com/assets/24657039/21524370/3ec1dae2-cd1e-11e6-8730-a333d5b8bd1a.jpg)

**Comment by AiKiHack** [comment]
You must download from branches 9 or 10 not from master :-)
